In [45]:
import pandas as pd
import numpy as np
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, make_scorer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import BayesianRidge
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import GridSearchCV
from pandas.api.types import is_list_like
from sklearn.linear_model import SGDRegressor
import numpy as np
from time import time
import missingno
from imputation import get_data, custom_pipe, inverse_prep


%reload_ext autoreload
%autoreload 2

In [54]:
df = get_data()

model = custom_pipe(df, RandomForestRegressor())


# Initialize KFold for cross-validation
kf = KFold(n_splits=5, shuffle=True, random_state=42)

outputs =[]
for train_idx, test_idx in kf.split(df):
    model.fit(df.loc[train_idx, :])
    outputs.append(model.transform(df.loc[test_idx, :]))

In [ ]:
x_in = df.loc[test_idx, :]
y_out = inverse_prep(model, y)

In [51]:
imputed_indices = np.argwhere(x_in.isna())

In [52]:
x_in.values[imputed_indices[:,0], imputed_indices[:, 1]]
y_out.values[imputed_indices[:, 0], imputed_indices[:, 1]]

array([431.4661654135338, 107737.18371347361, 0.2914787901595898,
       1632.5488285417898, 116614.16739038762, 0.2833834586466165,
       431.4661654135338, 97160.10869565218, 0.2833834586466165,
       431.4661654135338, 97160.10869565218, 0.4152418962261109,
       431.4661654135338, 97160.10869565218, 0.2833834586466165,
       10229.62882820039, 431.4661654135338, 97160.10869565218,
       0.2833834586466165, 431.4661654135338, 97160.10869565218,
       0.2833834586466165, 431.4661654135338, 109693.53857917029,
       0.2833834586466165, 431.4661654135338, 97160.10869565218,
       0.2833834586466165, 431.4661654135338, 97160.10869565218,
       0.2833834586466165, 51644.53634085213, 431.4661654135338,
       115784.65366862147, 0.688290402289784, 142315.78358208956,
       431.4661654135338, 97160.10869565218, 0.2833834586466165,
       431.4661654135338, 133437.74516030395, 0.2833834586466165,
       431.4661654135338, 97293.52438083004, 0.2833834586466165,
       431.4661654135338, 97160.10869565218, 0.2833834586466165,
       431.4661654135338, 110496.13038596761, 0.3533864065402731,
       431.4661654135338, 118893.69288612047, 0.2833834586466165,
       1734.6169277521008, 101426.27963481496, 0.5088524316278479,
       431.4661654135338, 125006.92146215634, 0.2833834586466165,
       431.4661654135338, 98261.98223308045, 0.2833834586466165,
       431.4661654135338, 97160.10869565218, 0.4509430242678889,
       431.4661654135338, 97160.10869565218, 0.9026899522479973,
       1655.766888204672, 97160.10869565218, 1.0601514539129493,
       9846.661975231913, 898.6808966770509, 114087.16476206911,
       0.3183031104090923, 492.39712004519566, 141324.4461817154,
       0.6239470791545133, 1336.732563169511, 101574.63328944011,
       1.5217598082640058, 675.0178983992135, 118042.98094883497,
       1.0872812618904333, 1435.2000381678226, 116939.54149059232,
       0.815266631232056, 1652.3988305296327, 147533.9667353604,
       0.549578370582392, 2032.1901203514249, 97160.10869565218,
       0.5685543448114379, 1567.5697033940166, 98832.40325247789,
       0.7511964108247946, 431.4661654135338, 120186.5137499859,
       0.7975211326330673, 767.3039523356595, 99884.96739875985,
       0.4310330422208648, 431.4661654135338, 97160.10869565218,
       0.2833834586466165, 431.4661654135338, 97160.10869565218,
       0.2833834586466165, 4908.212895939709, 523.3804345907892,
       117047.64737617868, 0.5050864185582804, 12047.009582232024,
       432.88503247256796, 97160.10869565218, 0.2833834586466165,
       431.4661654135338, 118098.07117607584, 0.2833834586466165,
       431.4661654135338, 97160.10869565218, 0.2833834586466165,
       7484.544586789103, 431.4661654135338, 114098.70645718824,
       0.2833834586466165, 431.4661654135338, 97160.10869565218,
       0.2833834586466165, 9759.16414676842, 431.4661654135338,
       105526.18598730251, 0.2833834586466165, 431.4661654135338,
       97160.10869565218, 0.2833834586466165, 10240.048184765823,
       431.4661654135338, 144034.2750107534, 0.2833834586466165,
       431.4661654135338, 97160.10869565218, 0.2833834586466165,
       431.4661654135338, 97160.10869565218, 0.5422464462471153,
       431.4661654135338, 117474.74246267186, 0.2833834586466165,
       431.4661654135338, 97160.10869565218, 0.2833834586466165,
       431.4661654135338, 135024.64122032144, 0.2833834586466165,
       431.4661654135338, 97160.10869565218, 0.2833834586466165,
       431.4661654135338, 97160.10869565218, 0.2833834586466165,
       431.4661654135338, 97160.10869565218, 0.2833834586466165,
       431.4661654135338, 108798.8094052615, 0.2833834586466165,
       431.4661654135338, 97160.10869565218, 0.2833834586466165,
       431.4661654135338, 97160.10869565218, 0.2833834586466165,
       431.4661654135338, 97160.10869565218, 0.2833834586466165,
       431.4661654135338, 97160.10869565218, 0.2833834586466165,
       431.4661654135338, 97160.10869565218, 0.2833834586466165,
       431.4661654135338, 99984.73767595361, 0.2833834586466165,
       431.4661654135338, 112539.76459906623, 0.2833834586466165,
       431.4661654135338, 139662.92958703538, 0.2833834586466165,
       583.6086328825817, 131529.35969726543, 0.46580008251234656,
       4822.179123616401, 112082.7445210983, 132988.41018671705,
       102747.70037492379, 967.4784861436915, 0.6909669730928524,
       8366.196866495835, 431.4661654135338, 97160.10869565218,
       0.39475714581456517, 431.4661654135338, 112734.01523127,
       0.2833834586466165, 431.4661654135338, 156188.2440700049,
       0.4190970416758416, 431.4661654135338, 105277.60573562267,
       0.2833834586466165, 431.4661654135338, 100378.32567697676,
       0.2833834586466165, 431.4661654135338, 97160.10869565218,
       0.2833834586466165, 4461.76634069723, 431.4661654135338,
       111633.75530443163, 0.2833834586466165, 431.4661654135338,
       143066.63552431713, 0.2833834586466165, 857.627906775696,
       124295.49090379883, 0.5959313498722287, 467.4302837060265,
       0.39659000350503293, 431.4661654135338, 127051.42265900485,
       0.7574390150613458, 431.4661654135338, 125802.93896937261,
       0.49902589120849883, 113442.69518651675, 431.4661654135338,
       121318.35093955151, 0.2833834586466165, 5299.883247022094,
       431.4661654135338, 97160.10869565218, 0.2833834586466165,
       431.4661654135338, 126653.67825346615, 0.2833834586466165,
       106248.281423718, 431.4661654135338, 97160.10869565218,
       0.2833834586466165, 431.4661654135338, 97160.10869565218,
       0.2833834586466165, 6878.787201705359, 431.4661654135338,
       97160.10869565218, 0.2833834586466165, 431.4661654135338,
       97160.10869565218, 0.2833834586466165, 431.4661654135338,
       97160.10869565218, 0.47432198748102317, 431.4661654135338,
       105780.74632153416, 0.2833834586466165, 431.4661654135338,
       97160.10869565218, 0.2833834586466165, 3510.6076193422214,
       5271.257476710177, 4298.6590843943195, 431.4661654135338,
       119352.12504999555, 0.2833834586466165, 431.4661654135338,
       130729.52768682686, 0.2833834586466165, 431.4661654135338,
       97160.10869565218, 0.2833834586466165, 431.4661654135338,
       97160.10869565218, 0.2833834586466165, 431.4661654135338,
       97160.10869565218, 0.2833834586466165, 431.4661654135338,
       97160.10869565218, 0.2833834586466165, 1137.1268785443076,
       135098.93914710602, 0.2833834586466165, 431.4661654135338,
       97160.10869565218, 0.2833834586466165, 431.4661654135338,
       97160.10869565218, 0.2833834586466165, 431.4661654135338,
       97160.10869565218, 0.2833834586466165, 431.4661654135338,
       97160.10869565218, 0.2833834586466165, 431.4661654135338,
       125040.41380546388, 0.2833834586466165, 431.4661654135338,
       97160.10869565218, 0.2833834586466165, 5775.644040083468,
       108454.19932181315, 431.4661654135338, 97160.10869565218,
       0.2833834586466165, 431.4661654135338, 117520.5770688754,
       0.2833834586466165, 431.4661654135338, 97160.10869565218,
       0.2833834586466165, 431.4661654135338, 97160.10869565218,
       0.2833834586466165, 431.4661654135338, 97160.10869565218,
       0.2833834586466165, 8197.078805687102, 431.4661654135338,
       97160.10869565218, 0.2833834586466165, 431.4661654135338,
       125426.10287503414, 0.2833834586466165, 431.4661654135338,
       97160.10869565218, 0.2833834586466165, 431.4661654135338,
       124689.02744060861, 0.2833834586466165, 431.4661654135338,
       97160.10869565218, 0.2833834586466165, 431.4661654135338,
       97160.10869565218, 0.2833834586466165, 431.4661654135338,
       116502.19468729763, 0.2833834586466165, 431.4661654135338,
       97160.10869565218, 0.2833834586466165, 431.4661654135338,
       144599.46135733378, 0.2833834586466165, 1262.168379430199,
       97160.10869565218, 0.34958169891754065, 431.4661654135338,
       97160.10869565218, 0.8454398533027704, 1309.1011642386563,
       97160.10869565218, 0.2833834586466165, 1025.199170771298,
       116166.27054749768, 0.2833834586466165], dtype=object)

In [53]:
display(x_in[x_in["state"] == "Wyoming"])
display(y_out[y_out["state"]=="Wyoming"])

,state,sector,state_sector_tot_headcount,state_sector_salary,ds_state_sector_headcount,ds_state_sector_salary,ds_state_sector_pct,ds_state_tot_headcount,ds_state_mdn_salary
397,Wyoming,Transportation and Warehousing,12570.0,52690.0,NaN,NaN,NaN,40.0,139970.0
805,Wyoming,Health Care and Social Assistance,33160.0,43520.0,NaN,NaN,NaN,40.0,139970.0
856,Wyoming,"Arts, Entertainment, and Recreation",3510.0,30340.0,NaN,NaN,NaN,40.0,139970.0

,state,sector,state_sector_tot_headcount,state_sector_salary,ds_state_sector_headcount,ds_state_sector_salary,ds_state_sector_pct,ds_state_tot_headcount,ds_state_mdn_salary
78,Wyoming,Transportation and Warehousing,12570.0,52690.0,431.466165,139662.929587,0.283383,40.0,139970.0
166,Wyoming,Health Care and Social Assistance,33160.0,43520.0,431.466165,130729.527687,0.283383,40.0,139970.0
177,Wyoming,"Arts, Entertainment, and Recreation",3510.0,30340.0,431.466165,125040.413805,0.283383,40.0,139970.0